version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - vtb-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: "${POSTGRES_DB}"
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - /var/lib/postgresql/data

networks:
  vtb-network: